#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(git dart flutter)
s-checkdeps "${DEPS[@]}"

TO=$HOME/.local/flutter

[[ ! -d $TO/.git ]] && git clone https://github.com/flutter/flutter --branch stable --single-branch "$TO"

git -C "$TO" pull
