#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(curl bash)
s-checkdeps "${DEPS[@]}"

LOCAL_BIN="$HOME/.local/bin"

if [[ ! -x $(command -v composer) ]]; then
    cd /tmp

    EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
        echo >&2 'ERROR: Invalid installer checksum'
        rm composer-setup.php
        exit 1
    fi

    php composer-setup.php --quiet
    RESULT=$?
    rm composer-setup.php
    exit "$RESULT"

    mv /tmp/composer.phar "$LOCAL_BIN/composer"

    "$LOCAL_BIN/composer" --version
fi

PHPACTOR_LOCATION="$HOME/Builds/phpactor"
if [[ ! -x $(command -v phpactor) ]]; then
    [[ ! -d $PHPACTOR_LOCATION/.git ]] && git clone git@github.com:phpactor/phpactor "$PHPACTOR_LOCATION"

    cd "$PHPACTOR_LOCATION"
    composer update && composer install
    ln -s "$PHPACTOR_LOCATION/bin/phpactor" "$LOCAL_BIN/phpactor"

    "$LOCAL_BIN/phpactor" --version
fi

if [[ ! -f $HOME/.symfony5/bin/symfony ]]; then
    wget https://get.symfony.com/cli/installer -O - | bash
fi

exit
