#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(go)
s-checkdeps "${DEPS[@]}"

if [[ ! -x $(command -v golangci-lint) ]]; then
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

    golangci-lint --version
fi
