#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

if [[ -x $(command -v psql) ]]; then
    postgres_version=$(psql --version | awk '{print substr($3, 0, 2)}')
    hba_conf="/etc/postgresql/$postgres_version/main/pg_hba.conf"

    # sudo systemctl enable postgresql
    # sudo systemctl start postgresql

    # set password to postgres user
    sudo -u postgres psql -c "\password"

    # create $USER
    sudo -u postgres createuser --createdb --createrole --pwprompt "$USER" # permission to create database and set password

    correct_auth="local all all password"
    if ! sudo grep -i "$correct_auth" "$hba_conf"; then
        echo -n "$correct_auth" | sudo tee -a "$hba_conf"
        sudo systemctl restart postgresql
    fi
fi
