#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# debug options
set -euo pipefail

DEPS=(emacs git doom)
s-checkdeps "${DEPS[@]}"

EMACS_D_HOME="$HOME/.emacs.d"
DOOM_HOME="$HOME/.config/emacs"

[[ -d $EMACS_D_HOME ]] && rm -rf "$EMACS_D_HOME"

if [[ ! -x "$DOOM_HOME/bin/doom" ]]; then
    git clone https://github.com/hlissner/doom-emacs "$DOOM_HOME"
    "$DOOM_HOME/bin/doom" install
fi

# Update
"$DOOM_HOME/bin/doom" upgrade
"$DOOM_HOME/bin/doom" doctor

exit
