#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(wget)
s-checkdeps "${DEPS[@]}"

DOTNET_VERSION=7.0
DOTNET_INSTALL_PATH=$HOME/.local/bin/dotnet-install
[[ -x $DOTNET_INSTALL_PATH ]] && wget https://dot.net/v1/dotnet-install.sh -O "$DOTNET_INSTALL_PATH"

"$DOTNET_INSTALL_PATH" -h
"$DOTNET_INSTALL_PATH" --channel "$DOTNET_VERSION"

exit
