#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

s-base-emacs
s-pack-golang
s-pack-scheme
s-ops-containers

# Save last state to usb-stick
if [[ -x $(command -v qas) ]]; then
    qas --grab
    qas --archive bin,lar,annotations # TODO: save to usb-stick

    STICK=/media/$USER/MOAR
    cp "$HOME/Downloads/archived" "$STICK"
fi
