#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

BIN=$HOME/.local/bin

s-echo "Babashka"
if [[ ! -x $BIN/bb ]]; then
    URL="https://raw.githubusercontent.com/babashka/babashka/master/install"
    INSTALL_PATH="/tmp/install"

    wget -c $URL -P /tmp
    sed -i 's+/usr/local/bin+$HOME/.local/bin+g' "$INSTALL_PATH"
    bash "$INSTALL_PATH"
    rm "$INSTALL_PATH"
fi

s-echo "Lein"
if [[ ! -x $BIN/lein ]]; then
    URL="https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    wget -c $URL -P "$BIN"
    chmod +x "$BIN/lein"
fi

exit

s-echo "CLOJURE-LSP"
if [[ ! -x $BIN/clojure-lsp ]]; then
    URL="https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install"
    INSTALLER_PATH="/tmp/clojure-lsp-install"

    wget -c $URL -O "$INSTALLER_PATH"
    sed -i 's+/usr/local/bin+$HOME/.local/bin+g' "$INSTALLER_PATH"
    bash "$INSTALLER_PATH"

    [[ -x $BIN/clojure-lsp ]] && "$BIN/clojure-lsp" --version && rm "$INSTALLER_PATH"
fi
