#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(cmake)
s-checkdeps "${DEPS[@]}"

# [[ -x $(command -v conan) ]] && conan
# conan profile new default --detect
# conan profile update settings.compiler.libcxx=libstdc++11 default

BUILDS=$HOME/Builds

[[ ! -d $BUILDS/libqgit2/.git ]] && git clone https://invent.kde.org/libraries/libqgit2 "$BUILDS/libqgit2"
cd "$BUILDS/libqgit2"
cmake .
make
sudo make install

# -- Installing: /usr/local/lib/libqgit2.a
# -- Installing: /usr/local/include/qgit2/qgitblob.h

cd "$BUILDS"
