#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG SETTINGS
set -euo pipefail

# * CHECKER
DEPS=(bash wget curl)
s-checkdeps "${DEPS[@]}"

[[ ! -x $(command -v k3s) ]] && curl -sfL https://get.k3s.io | sh -

# K3D
[[ ! -x $(command -v k3d) ]] && wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

# OKTETO
[[ ! -x $(command -v okteto) ]] && curl https://get.okteto.com -sSfL | sh
