#!/usr/bin/env bash

# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.


# Debug Options
set -euo pipefail

DEPS=(curl bash awk)
s-checkdeps "${DEPS[@]}"

BUILDS="$HOME/Builds"
LOCAL_BIN="$HOME/.local/bin"

# =============== SDKMAN
if [[ ! -f "$HOME/.sdkman/bin/sdkman-init.sh" ]]; then
     curl -s "https://get.sdkman.io" | bash
fi

if [[ ! -f "$HOME/.jbang/bin/jbang" ]]; then
    curl -Ls https://sh.jbang.dev | bash -s - app setup
fi



# =============== GOOGLE-JAVA-FORMAT - https://github.com/google/google-java-format
TAGS_URL="https://api.github.com/repos/google/google-java-format/tags"
VERSION="$(curl -s $TAGS_URL | awk '/name/ {version=substr($2,2,7); print version; exit}')"
URL="https://github.com/google/google-java-format/releases/download/"
wget "$URL/$VERSION/google-java-format_linux-x86-64" -O "$LOCAL_BIN"/google-java-format
chmod +x "$LOCAL_BIN"/google-java-format
"$LOCAL_BIN"/google-java-format --version

exit

# ================== GRAAL - https://github.com/graalvm/graalvm-ce-builds/releases/
if [[ ! -x "$LOCAL_BIN/gu" ]]; then
    TAGS_URL="https://api.github.com/repos/graalvm/graalvm-ce-builds/tags"
    VERSION=$( curl -s $TAGS_URL | awk '/name/ {version=substr($2,2,10); print version; exit}')
    graal_location="$BUILDS/graalvm-community-openjdk-${VERSION}+9.1"
    current="graalvm-community-${VERSION}_linux-x64_bin.tar.gz"
    URL="https://github.com/graalvm/graalvm-ce-builds/releases/download/${VERSION}/${current}"

    wget -c "$URL" -P /tmp
    tar xf "/tmp/$current" -C "$BUILDS"

    mv "${graal_location}" "$HOME/Builds/graal"
    ln -sf "$HOME/Builds/graal/bin/gu" "$LOCAL_BIN/gu"
    "$LOCAL_BIN/gu" --version
fi

if [[ ! -x "$LOCAL_BIN/eclipse" ]]; then
    ECLIPSE_URL='https://eclipse.c3sl.ufpr.br/oomph/epp/2022-06/R/eclipse-inst-jre-linux64.tar.gz'
    wget -c "$ECLIPSE_URL" -P "$BUILDS"
    tar -xf "$BUILDS/eclipse-inst-jre-linux64.tar.gz" -C "$BUILDS"
fi

# IDEA
if [[ ! -x "$LOCAL_BIN/idea" ]]; then
    URL="https://download.jetbrains.com/idea/ideaIC-2022.3.tar.gz"

    wget -c $URL -P /tmp
    tar xf /tmp/ideaIC-2022.3.tar.gz -C "$BUILDS"
    ln -sf "$BUILDS/idea-IC-223.7571.182/bin/idea.sh" "$LOCAL_BIN/idea"
fi

if [[ ! -x "$LOCAL_BIN/spring-tool-suite" ]]; then
    STS_URL='https://download.springsource.com/release/STS4/4.15.3.RELEASE/dist/e4.24/spring-tool-suite-4-4.15.3.RELEASE-e4.24.0-linux.gtk.x86_64.tar.gz'
    wget -c "$STS_URL" -P "$BUILDS"
    tar -xf "$BUILDS/spring-tool-suite-4-4.15.3.RELEASE-e4.24.0-linux.gtk.x86_64.tar.gz" -C "$BUILDS"
    ln -sf "$BUILDS/sts-4.15.3.RELEASE/SpringToolSuite4" "$LOCAL_BIN/spring-tool-suite"
fi

if [[ ! -x "$LOCAL_BIN/netbeans" ]]; then
    BEANS_URL='https://dlcdn.apache.org/netbeans/netbeans/15/netbeans-15-bin.zip'
    wget -c "$BEANS_URL" -P "$BUILDS"
    unzip "$BUILDS/netbeans-15-bin.zip" -d "$BUILDS"
    ln -sf "$BUILDS/netbeans/bin/netbeans" "$LOCAL_BIN/netbeans"
fi
