#!/usr/bin/env bash

# debug options
set -euo pipefail

DEPS=(emacs git doom)
s-checkdeps "${DEPS[@]}"

EMACS_D_HOME="$HOME/.emacs.d"
DOOM_HOME="$HOME/.config/emacs"

[[ -d $EMACS_D_HOME ]] && rm -rf "$EMACS_D_HOME"

if [[ ! -x "$DOOM_HOME/bin/doom" ]]; then
    git clone https://github.com/hlissner/doom-emacs "$DOOM_HOME"
    "$DOOM_HOME/bin/doom" install
fi

# Update
"$DOOM_HOME/bin/doom" sync -u

exit
