#!/usr/bin/env bash

# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.

# DEBUG OPTIONS
set -euo pipefail

LOCAL_DIR="$HOME/.local"
BUILDS_DIR="$HOME/Builds"

curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

git clone --single-branch --depth=1 https://github.com/ndmitchell/hoogle

ghcup install hls
