#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# HARE LANG INSTALL
# INFO: https://harelang.org/installation

BUILDS_HOME="$HOME/Builds"
LOCAL_FOLDER="$HOME/.local"

QBE_LOCATION="$BUILDS_HOME/qbe"
[[ ! -d $QBE_LOCATION/.git ]] && git clone git://c9x.me/qbe.git "$QBE_LOCATION" || git -C "$QBE_LOCATION" pull

cd "$QBE_LOCATION"
make
make PREFIX="$LOCAL_FOLDER" install

SCDOC_LOCATION="$BUILDS_HOME/scdoc"
[[ ! -d $SCDOC_LOCATION/.git ]] && git clone https://git.sr.ht/~sircmpwn/scdoc "$SCDOC_LOCATION" || git -C "$SCDOC_LOCATION" pull

cd scdoc
make
make PREFIX="$LOCAL_FOLDER" install

HAREC_FOLDER="$BUILDS_HOME/harec"
[[ ! -d "$HAREC_FOLDER"/.git ]] && git clone https://git.sr.ht/~sircmpwn/harec "$HAREC_FOLDER" || git -C "$HAREC_FOLDER" pull

cd "$HAREC_FOLDER"

mkdir build
cd build
../configure
make
make PREFIX="$LOCAL_FOLDER" install

HARE_FOLDER="$BUILDS_HOME/hare"
[[ ! -d $HARE_FOLDER/.git ]] && git clone https://git.sr.ht/~sircmpwn/hare "$HARE_FOLDER" || git -C "$HARE_FOLDER" pull

cd "$HARE_FOLDER"

cp config.example.mk config.mk
make
make PREFIX="$LOCAL_FOLDER" install

exit
