#!/usr/bin/env bash

# ====================================

if [[ ! -d "$HOME/.local/swift" ]]; then
    url='https://download.swift.org/swift-5.7.1-release/ubuntu2004/swift-5.7.1-RELEASE/swift-5.7.1-RELEASE-ubuntu20.04.tar.gz'
    wget -c $url -P /tmp

    tar -xvzf /tmp/swift-*-RELEASE-ubuntu*.tar.gz -C "$HOME/.local/"
    mv "$HOME/.local/"swift-*-RELEASE-ubuntu* "$HOME/.local/swift"
fi

if [[ ! -x $(command -v swift-format) ]]; then
    folder="$HOME/Builds/swift-format"
    version=0.50700.1

    git clone https://github.com/apple/swift-format.git -C "$folder"
    cd swift-format
    git checkout "tags/$version"

    swift build -c release
    cp "$folder/.build/release/swift-format" "$HOME/.local/bin"
else
    git -C "$folder" pull
fi
