#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(sudo git make)
s-checkdeps "${DEPS[@]}"

# ENV VARS
BUILDS="$HOME/Builds"
BUILD_ROOT="$BUILDS/emacs"
INSTALL_DIR="$HOME/.local"
TAG=emacs-28.0.91

s-echo "Emacs - Installing local build"

[[ ! -d $BUILD_ROOT/.git ]] && git clone -b "$TAG" --single-branch --depth 1 "https://git.savannah.gnu.org/git/emacs" "$BUILD_ROOT"

[[ -d "$BUILD_ROOT/.git" ]] && git -C "$BUILD_ROOT" pull

cd "$BUILD_ROOT"
[[ -f Makefile ]] && make distclean
sh autogen.sh

cd "$BUILD_ROOT"
sh configure --prefix="$INSTALL_DIR" --with-modules --with-native-compilation --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-x --with-dbus --with-imagemagick --with-mailutils --with-gnutls --with-x-toolkit=gtk3

cd "$BUILD_ROOT"
make -j 4
make install

exit
