#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# debug options
set -euo pipefail
PREFIX="$HOME/.local"
BUILDS_DIR="$HOME/Builds"

# ===========================
# SBCL INSTALL

SBCL_BUILD_DIR="$BUILDS_DIR/sbcl"
SBCL_VERSION=sbcl-2.3.7
if [[ ! -f $PREFIX/bin/sbcl ]] && [[ ! -d "$SBCL_BUILD_DIR" ]]; then
    git clone \
        --single-branch \
        --depth=1 \
        --branch "$SBCL_VERSION" \
        git://git.code.sf.net/p/sbcl/sbcl \
        "$SBCL_BUILD_DIR"
fi

git -C "$SBCL_BUILD_DIR" pull

export -n SBCL_HOME

cd "$SBCL_BUILD_DIR"

sh make.sh --fancy --prefix="$PREFIX/bin"

# cd ./tests && sh ./run-tests.sh # test a lil more
# cd ./doc/manual && make #  documentation

sh install.sh --prefix="${HOME}/.local"

exit

# ===========================
# STUMPWM

export SBCL_HOME=$HOME/.local/lib/sbcl # set sbcl to local build
STUMPWM_LOCATION="$BUILDS_LOCATION/stumpwm"
STUMPWM_CONTRIB_LOCATION="$BUILDS_LOCATION/stumpwm-contrib"

[[ ! -d "$STUMPWM_LOCATION/.git" ]] && git clone https://github.com/stumpwm/stumpwm "$STUMPWM_LOCATION"
[[ ! -d "$STUMPWM_CONTRIB_LOCATION/.git" ]] && git clone https://github.com/stumpwm/stumpwm-contrib "$STUMPWM_CONTRIB_LOCATION"

git -C "$STUMPWM_LOCATION" pull
git -C "$STUMPWM_CONTRIB_LOCATION" pull

cd "$STUMPWM_LOCATION"
./autogen.sh
./configure --prefix="$PREFIX"
make -j4
make install

if ! grep 'Type=XSession' /usr/share/xsessions/stumpwm-local.desktop; then
    cat <<EOF | sudo tee -a "/usr/share/xsessions/stumpwm-local.desktop"
[Desktop Entry]
Encoding=UTF-8
Name=StumpWM-local
Comment=Local StumpWM build
Exec=$HOME/.local/bin/stumpwm
Type=XSession
EOF
fi

# ===================================================
# CLPM

CLPM_LOCATION="$BUILDS_LOCATION/clpm"

[[ ! -d $CLPM_LOCATION/.git ]] && git clone https://gitlab.common-lisp.net/clpm/clpm "$CLPM_LOCATION"

cd "$CLPM_LOCATION"

git submodule init
git submodule update
sbcl --script scripts/build-release.lisp

exit
