#!/usr/bin/env bash

# HARE LANG INSTALL
# INFO: https://harelang.org/installation

BUILDS_HOME="$HOME/Builds"
LOCAL_FOLDER="$HOME/.local"

QBE_LOCATION="$BUILDS_HOME/qbe"
if [[ ! -d $QBE_LOCATION/.git ]]; then
    git clone git://c9x.me/qbe.git "$QBE_LOCATION"
else
    git -C "$QBE_LOCATION" pull

    cd "$QBE_LOCATION" || return
    make
    make PREFIX="$LOCAL_FOLDER" install
fi

SCDOC_LOCATION="$BUILDS_HOME/scdoc"
if [[ ! -d $SCDOC_LOCATION/.git ]]; then
    git clone https://git.sr.ht/~sircmpwn/scdoc "$SCDOC_LOCATION"
else
    git -C "$SCDOC_LOCATION" pull

    cd scdoc || return
    make
    make PREFIX="$LOCAL_FOLDER" install
fi

HAREC_FOLDER="$BUILDS_HOME/harec"
if [[ ! -d "$HAREC_FOLDER"/.git ]]; then
    git clone https://git.sr.ht/~sircmpwn/harec "$HAREC_FOLDER"
else
    git -C "$HAREC_FOLDER" pull

    cd "$HAREC_FOLDER" || return

    mkdir build
    cd build || return
    ../configure
    make
    make PREFIX="$LOCAL_FOLDER" install
fi

HARE_FOLDER="$BUILDS_HOME/hare"
if [[ ! -d $HARE_FOLDER/.git ]]; then
    git clone https://git.sr.ht/~sircmpwn/hare "$HARE_FOLDER"
else
    git -C "$HARE_FOLDER" pull

    cd "$HARE_FOLDER" || return

    cp config.example.mk config.mk
    make
    make PREFIX="$LOCAL_FOLDER" install
fi

exit
