#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(python bash)
s-checkdeps "${DEPS[@]}"

COMMAND="python3 -m pip install --upgrade"

tools=(black pipenv pyflakes pytest isort nose poetry)
libs=(beautifulsoup4 interval)
apps=(yt-dlp cryptography)

groups=("${tools[@]}" "${libs[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist "$COMMAND" "${group[@]}"
done

exit

[[ ! -x $(command -v poetry) ]] && {
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    poetry self update
    # poetry completions zsh >~/.zfunc/_poetry
}
