#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(ruby gem)
s-checkdeps "${DEPS[@]}"

essential=(bundler rake)
tools=(reek rufo rubocop solargraph pry taglib-ruby)

groups=("${essential[@]}" "${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist "gem install" "$group"
    s-dolist "gem update" "$group"
done
