#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(curl)
s-checkdeps "${DEPS[@]}"

[[ ! -f ~/.cargo/env ]] && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

. "$HOME/.cargo/env"

exit

tools=(starship)
apps=(fd-find ripgrep exa bat procs sd du-dust tokei)

groups=("${tools[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist 'cargo install --locked' "$group"
done
