#!/usr/bin/env bash

# * Debug Options
set -euo pipefail

DEPS=(sudo guix wget bash)
s-checkdeps "${DEPS[@]}"
COMMAND="guix install"

packages=(nss-certs font-dejavu)
apps=(haunt)
langs=(guile guile-readline)

groups=("${packages[@]}" "${apps[@]}" "${langs[@]}")

for group in "${groups[@]}"; do
	s-dolist "$COMMAND" "${group[@]}"
done
