#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(npm)
s-checkdeps "${DEPS[@]}"

ESSENTIAL=(npm yarn)
TOOLS=(stylelint js-beautify prettier)
LANGS=(typescript)

groups=("${ESSENTIAL[@]}" "${TOOLS[@]}" "${LANGS[@]}")

for group in "${groups[@]}"; do
	s-dolist 'npm install --global' "$group"
	s-dolist 'npm update --global' "$group"
done

if [[ -x $(command -v bun) ]] && curl https://bun.sh/install | bash
