#!/usr/bin/env zsh

# Debug Options
set -euo pipefail

DEPS=(curl bash)
s-checkdeps "${DEPS[@]}"

BUILDS="$HOME/Builds"

# * ECLIPSE

ECLIPSE_URL='https://eclipse.c3sl.ufpr.br/oomph/epp/2022-06/R/eclipse-inst-jre-linux64.tar.gz'
wget -c "$ECLIPSE_URL" -P "$BUILDS"
tar -xf "$BUILDS/eclipse-inst-jre-linux64.tar.gz"

# * SPRING TOOLS SUITE

STS_URL='https://download.springsource.com/release/STS4/4.15.3.RELEASE/dist/e4.24/spring-tool-suite-4-4.15.3.RELEASE-e4.24.0-linux.gtk.x86_64.tar.gz'
wget -c "$STS_URL" -P "$BUILDS"
tar -xf "$BUILDS/spring-tool-suite-4-4.15.3.RELEASE-e4.24.0-linux.gtk.x86_64.tar.gz"
