#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(npm)
s-checkdeps "${DEPS[@]}"

[[ ! -x $HOME/.bun/bin/bun ]] && curl https://bun.sh/install | bash
[[ ! -x $HOME/.deno/bin/deno ]] && curl -fsSL https://deno.land/install.sh | bash

essential=(npm yarn)
langs=(typescript)
tools=(stylelint js-beautify prettier ts-node typescript-language-server)
frameworks=(@nestjs/cli express-generator)

all=("${essential[@]}" "${tools[@]}" "${frameworks[@]}" "${langs[@]}")

for single in "${all[@]}"; do
	s-dolist 'npm install --global' "$single"
done

# Update all packages
npm update --global

exit 0
