#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(python bash)
s-checkdeps "${DEPS[@]}"

COMMAND="python3 -m pip install --upgrade"

TOOLS=(black pipenv pyflakes pytest isort nose poetry)
s-dolist "$COMMAND" "${TOOLS[@]}"

LIBS=(beautifulsoup4 interval)
s-dolist "$COMMAND" "${LIBS[@]}"

APPS=(yt-dlp cryptography)
s-dolist "$COMMAND" "${APPS[@]}"

exit

[[ ! -x $(command -v poetry) ]] && {
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
    poetry self update
    # poetry completions zsh >~/.zfunc/_poetry
}
