#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(curl)
s-checkdeps "${DEPS[@]}"

# RUST TOOLCHAIN
[[ ! -f ~/.cargo/env ]] && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# CARGO
. "$HOME/.cargo/env"

tools=(starship)
tasks=(cargo-watch cargo-tarpaulin)
apps=(fd-find ripgrep exa bat procs sd du-dust tokei)

groups=("${tools[@]}" "${tasks[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist 'cargo install --locked' "$group"
done

# RUSTUP
tools=(rust-analyzer clippy rustfmt cargo-audit)

groups=("${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist 'rustup component add' "$group"
done

# RUST ANALYZER
ln -sf "$(rustup which --toolchain stable rust-analyzer)" "$HOME/.local/bin/rust-analyzer"

exit
