#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(python bash)
s-checkdeps "${DEPS[@]}"

COMMAND="python3 -m pip install --upgrade"

tools=(black pipenv pyflakes pytest isort nose pyperclip)
libs=(beautifulsoup4 interval)
apps=(cryptography)

groups=("${tools[@]}" "${libs[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist "$COMMAND" "${group[@]}"
done

# if [[ ! -x $(command -v poetry) ]]; then
#     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
# else
#     poetry self update
# fi
