#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG SETTINGS
set -euo pipefail

if [[ -x $(command -v gota) ]]; then
    gota --pack --filter php --verbose
    gota --pack --filter python --verbose
    gota --pack --filter javascript --verbose
    gota --pack --filter rust --verbose
fi

[[ -x $(command -v podman) ]] && gota --misc --filter containers --verbose
[[ -x $(command -v flatpak) ]] && gota --distro --filter flatpak --verbose
[[ -x $(command -v guix) ]] && gota --distro --filter guix --verbose
[[ -x $(command -v emacs) ]] && s-base-emacs
[[ -x $(command -v onur) ]] && onur grab
