#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt wget systemctl timedatectl fc-cache firewalld)
s-checkdeps "${DEPS[@]}"

INSTALL='sudo apt-get install -y'

s-echo "Welcome to Debian '$(cat /etc/debian_version)'"

s-echo "Upgrading System"
sudo apt update
sudo apt upgrade -y

s-echo "Pre Install"
s-echo "Enable Multi-Arch"
sudo dpkg --add-architecture i386

s-echo "System Packages - Installation"

amd=(firmware-linux-nonfree amd64-microcode firmware-amd-graphics libgl1-mesa-dri libglx-mesa0 mesa-utils libgl1-mesa-glx mesa-vulkan-drivers xserver-xorg-video-all libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386 radeontop)
cli=(htop elinks libnotify-bin ranger aria2 neofetch)
debian=(build-essential aptitude apt-file gdebi apt-listbugs apt-listchanges reportbug)
fonts=(fonts-hack fonts-dejavu fonts-jetbrains-mono ttf-ancient-fonts fonts-nanum ttf-mscorefonts-installer cmigemo)
gnu=(bash gcc make vrms info wget parallel gawk screen parted)
laptop=(acpi lm-sensors lshw libinput-tools) #acpid tlp vainfo i965-va-driver libvdpau-va-gl1 libiw-dev acpi-call dialog sysstat hddtemp
kde=(okular kate ktorrent kdenlive elisa kamoso breeze-gtk-theme kde-config-sddm plasma-workspace-wayland)
wayland=(wl-clipboard bemenu foot clipman grimshot xwayland mako-notifier wofi gammastep sway swaybg swaylock swayidle brightnessctl)
wm=(blueman udiskie alacritty)
# wlroots=(libdrm-dev libseat-dev glslang-tools libxcb-composite0-dev  libavutil-dev libavcodec-dev libavformat-dev libgbm-dev)
# wf-shell(libglm-dev libwf-config-dev wayfire-dev libpulse-dev libinotifytools0-dev libgtk-layer-shell-dev)
user=(firefox libreoffice gimp xdg-utils imagemagick aspell aspell-pt-br calibre pandoc obs-studio inkscape)
system=(git ssh curl unzip tmux zip p7zip p7zip-full recutils at usbutils lsof atool time entr tree bc strace ltrace cpio lhasa lzop rsync pv texinfo autoconf automake socat)
shell=(bash-completion shellcheck fish)
sound=(pipewire pipewire-pulse wireplumber pulseaudio-utils)
media=(ffmpeg mpv libtag1-dev vorbis-tools gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly libavcodec58)

all=("${debian[@]}"
	"${system[@]}"
	"${gnu[@]}"
	"${shell[@]}"
	"${media[@]}"
	"${sound[@]}"
	"${user[@]}"
	"${wm[@]}"
	"${wayland[@]}"
	"${kde[@]}"
	"${cli[@]}"
	"${laptop[@]}"
	"${amd[@]}"
	"${fonts[@]}")

for i in "${all[@]}"; do
	s-echo "$INSTALL $i"
	$INSTALL $i
done

s-echo "Post Install"

sudo apt -y build-dep emacs
sudo apt-file update                 # update Debian database
sudo usermod -a -G video,input $USER # brightnessctl acess

s-echo "Clean up"

sudo apt remove -y firefox-esr
sudo apt purge -y "*nvidia*"

# Locales
sudo dpkg-reconfigure locales
