#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(apt-get bash)
s-checkdeps "${DEPS[@]}"

COMMAND='sudo pacman -S --noconfirm'

# PROGRAMMING LANGUAGES
LANGS_HOBBY=(guile sbcl libfixposix) # libssl-dev libzstd-dev
s-dolist "$COMMAND" "${LANGS_HOBBY[@]}"

LANGS_WORK=(jre17-openjdk jdk17-openjdk clang)
s-dolist "$COMMAND" "${LANGS_WORK[@]}"

# PROGRAMMING EDITORS
EDITORS=(zile vim neovim)
s-dolist "$COMMAND" "${EDITORS[@]}"

# PROGRAMMING TOOLS
TOOLS=(jq subversion mercurial editorconfig-checker direnv fd tidy ripgrep shfmt) # libpq-dev git-email gnome-keyring
s-dolist "$COMMAND" "${TOOLS[@]}"

exit
