#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

PAM_AUTH='/etc/pam.d/system-auth'

# ONLY_NEW_PASSWORDS
/usr/bin/echo auth sufficient pam_unix.so likeauth nullok >>$PAM_AUTH
/usr/bin/echo password sufficient pam_unix.so nullok use-authtok md5 shadow remember=5 $PAM_AUTH

# STRONG_PASS_ONLY
/usr/bin/echo /lib/security/$ISA/pam_cracklib.so retry=3 minlen=8 lcredit=-1 ucredit=-2 dcredit=-2 ocredit=-1 $PAM_AUTH

# CHECK_EMPTY_PASS
/usr/bin/cat /etc/shadow | awk -F: '($2==""){print $1}'

# BOOT_READONLY

# DISABLE-ROOT
/usr/bin/sudo /usr/bin/passwd -l root
