#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo dnf)
s-checkdeps "${DEPS[@]}"

sudo dnf install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(
        rpm -E
        %fedora
    ).noarch.rpm
sudo dnf install \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(
        rpm
        -E %fedora
    ).noarch.rpm
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" \
    --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video

INSTALL=sudo dnf install -y

media=(mpv ffmpeg mpc mpd ncmpcpp)
sound=(pipewire pipewire-pulse lib32-pipewire pipewire-docs) # wireplumber pulseaudio-utils
groups=("${media[@]}" "${sound[@]}")

for group in "${groups[@]}"; do
    s-dolist "$INSTALL" "$group"
done

exit
