#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

# * CHECKER
DEPS=(bash sudo zae rsync)
s-checkdeps "${DEPS[@]}"

DISTRO="$(s-distro-name)"

case "$DISTRO" in
    "Debian GNU/Linux") s-distro-debian ;;
    "Fedora GNU/Linux") s-distro-fedora ;;
    "Ubuntu GNU/Linux") s-distro-ubuntu ;;
    "Arch GNU/Linux") s-distro-arch ;;
esac

# * SYSTEM
[[ -x $(command -v zae) ]] && zae update && zae upgrade

# * FOREIGN
s-distro-guix
s-distro-flatpak
s-distro-misc
