#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt flatpak)
s-checkdeps "${DEPS[@]}"

s-echo "Foreign packages"

if [[ ! -x $(command -v flatpak) ]]; then
	wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -P /tmp
	sudo apt-get -y /tmp/packages-microsoft-prod.deb
fi

if [[ ! -x $(command -v flatpak) ]]; then
	$INSTALL flatpak gnome-software-plugin-flatpak
	sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi

DEB_GET_LOCATION="$HOME/.local/bin/deb-get"
if [[ -x "$DEB_GET_LOCATION" ]]; then
	wget -c https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get -O "$DEB_GET_LOCATION"
	chmod +x "$DEB_GET_LOCATION"
fi

if [[ ! -x $(command -v insomnia) ]]; then
	echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" |
		sudo tee -a /etc/apt/sources.list.d/insomnia.list

	# Refresh repository sources and install Insomnia
	sudo apt-get update
	sudo apt-get install insomnia
fi

# if [[ ! -x $(command -v npm) ]]; then
# 	KEYRING=/usr/share/keyrings/nodesource.gpg
# 	VERSION=node_18.x
# 	DISTRO=bullseye

# 	wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
# 	gpg --no-default-keyring --keyring "$KEYRING" --list-keys

# 	echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
# 	echo "deb-src [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

# 	sudo apt update && sudo apt install -y nodejs=16.17.1-deb-1nodesource1 npm

# 	node --version
# 	npm --version
# fi

# if [[ ! $(command -v dbeaver) ]]; then
# 	[[ ! -f /tmp/dbeaver-ce_latest_amd64.deb ]] && wget -c "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb" -P /tmp
# 	sudo apt install -y /tmp/dbeaver-ce_latest_amd64.deb
# fi

exit
