#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# * Debug Options
set -euo pipefail

DEPS=(sudo guix bash)
s-checkdeps "${DEPS[@]}"

COMMAND="guix install"

guix pull
guix package -u

langs=(guile guile-readline php)
editors=(zile emacs)
misc=(nss-certs font-dejavu)
apps=(haunt guile-hall akku)
libs=(guile-git guile-json)

all=("${editors[@]}" "${langs[@]}" "${misc[@]}" "${apps[@]}" "${langs[@]}" "${libs[@]}")
for single in "${all[@]}"; do
	s-dolist "$COMMAND" "$single"
done
