#!/usr/bin/env bash

s-echo "Post Install"

paste() {
    file=$1
    to=$2

    [[ ! -f $to ]] && return

    if [[ ! $(grep -rni "$file" "$to") ]]; then
        echo "[[ -f $file ]] && source $file" >>$to
    fi
}

paste '$HOME/.config/bash/config.sh' "$HOME/.bashrc"
paste '$HOME/.config/bash/aliases.sh' "$HOME/.bashrc"
paste '$HOME/.config/env_variables' "$HOME/.profile"
paste '$HOME/.config/bash/profile.sh' "$HOME/.bash_profile"

# default folders
mkdir -pv "$HOME"/{Downloads,Pictures,Documents,Videos,Builds,Projects,.local/bin,.config/scripts}

# silent parallel, for good.
parallel --citation

# cache all system fonts
sudo fc-cache -fv

# create or update the manual page index caches
sudo mandb

if [[ -x $(command -v psql) ]]; then
    POSTGRES_VERSION=$(psql --version | awk '{print substr($3, 0, 2)}')
    HBA_CONF="/etc/postgresql/$POSTGRES_VERSION/main/pg_hba.conf"
    if ! sudo grep -i "$USER" "$HBA_CONF"; then
        sudo -u postgres createuser --createdb --createrole --pwprompt "$USER" # permission to create database and set password
        echo -n "local  all  all  md5" | sudo tee -a "$HBA_CONF"
        sudo systemctl restart postgresql
    fi
fi

# HELPERS
# --------------------------------------------------
