#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt wget systemctl timedatectl fc-cache firewalld)
s-checkdeps "${DEPS[@]}"

REMOVE='sudo apt remove -y'
PURGE='sudo apt purge -y'
INSTALL='sudo apt-get install -y'

s-echo "Welcome to Debian '$(cat /etc/debian_version)'"

# =================================

s-echo "Upgrading System"
sudo apt update
sudo apt upgrade -y

# =================================

s-echo "Pre Install"
s-echo "Enable Multi-Arch"
sudo dpkg --add-architecture i386

# =================================

s-echo "System Packages"

amd=(firmware-linux-nonfree amd64-microcode firmware-amd-graphics libgl1-mesa-dri libglx-mesa0 mesa-utils libgl1-mesa-glx mesa-vulkan-drivers xserver-xorg-video-all libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386 radeontop)
cli=(htop elinks libnotify-bin ranger aria2)
debian=(build-essential apt-listbugs apt-listchanges reportbug aptitude apt-file gdebi)
fonts=(fonts-hack fonts-dejavu fonts-jetbrains-mono ttf-ancient-fonts fonts-nanum)
gnu=(bash gcc make vrms info wget parallel gawk screen parted)
laptop=(acpi lm-sensors lshw libinput-tools) #acpid tlp vainfo i965-va-driver libvdpau-va-gl1 libiw-dev acpi-call dialog sysstat hddtemp
wayland=(wl-clipboard)
gtk=(arc-theme)
wm=(mpd mpc ncmpcpp playerctl)
user=(chromium firefox libreoffice gimp xdg-utils imagemagick aspell aspell-pt-br calibre pandoc obs-studio inkscape)
system=(git ssh curl unzip tmux zip p7zip p7zip-full recutils at usbutils lsof atool time entr tree bc strace ltrace cpio lhasa lzop rsync pv texinfo autoconf automake socat)
shell=(bash-completion shellcheck fish)
sound=(pipewire pipewire-pulse wireplumber pulseaudio-utils)
media=(ffmpeg mpv libtag1-dev vorbis-tools gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly libavcodec58)

groups=("${debian[@]}"
	"${system[@]}"
	"${gnu[@]}"
	"${shell[@]}"
	"${media[@]}"
	"${sound[@]}"
	"${user[@]}"
	"${wayland[@]}"
	"${wm[@]}"
	"${gtk[@]}"
	"${cli[@]}"
	"${laptop[@]}"
	"${amd[@]}"
	"${fonts[@]}")

for group in "${groups[@]}"; do
	s-dolist "$INSTALL" "$group"
done

# =================================
s-echo "Post Install"
sudo apt -y build-dep emacs
sudo apt-file update # update Debian database

# =================================
s-echo "Clean up"
UNUSED=(firefox-esr)
s-dolist "$REMOVE" "${UNUSED[@]}"

TOPURGE=(*nvidia*)
s-dolist "$PURGE" "${TOPURGE[@]}"
