#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(apt-get)
s-checkdeps "${DEPS[@]}"

INSTALL='sudo apt-get install -y'

lisp=(guile-3.0 guile-*-doc libzstd-dev)
php=(php php-common)
php_libs=(php-curl php-xml php-json php-mbstring php-zip php-*-xsl php-pgsql php-intl)
pg=(postgresql postgresql-client postgresql-contrib libpq-dev)
langs=(ruby-full)
langs_tools=(python3-pip)
mx=(emacs libgccjit0 libgccjit-12-dev libwebkit2gtk-4.0-dev libjansson-dev libjansson4)
tools=(jq git-email subversion mercurial libpq-dev editorconfig direnv fd-find shfmt meson cmake)
editors=(zile vim neovim tidy ripgrep)

groups=("${mx[@]}"
    "${langs[@]}"
    "${php[@]}"
    "${php_libs[@]}"
    "${lisp[@]}"
    "${langs_tools[@]}"
    "${editors[@]}"
    "${pg[@]}"
    "${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist "$INSTALL" "$group"
done

if [[ ! $(command -v insomnia) ]]; then
    echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" |
        sudo tee -a /etc/apt/sources.list.d/insomnia.list

    sudo apt-get update
    sudo apt-get install -y insomnia
fi

if [[ ! $(command -v dbeaver) ]]; then
    [[ ! -f /tmp/dbeaver-ce_latest_amd64.deb ]] && wget -c "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb" -P /tmp
    sudo apt install -y /tmp/dbeaver-ce_latest_amd64.deb
fi

exit
