#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt flatpak)
s-checkdeps "${DEPS[@]}"

s-echo "Foreign packages"

if [[ ! -x $(command -v flatpak) ]]; then
	$INSTALL flatpak gnome-software-plugin-flatpak
	sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi

if [[ ! -x $(command -v insomnia) ]]; then
	echo "deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all" |
		sudo tee -a /etc/apt/sources.list.d/insomnia.list

	# Refresh repository sources and install Insomnia
	sudo apt-get update
	sudo apt-get install insomnia
fi

exit

if [[ ! -x $(command -v npm) ]]; then
	KEYRING=/usr/share/keyrings/nodesource.gpg
	VERSION=node_16.x
	DISTRO=bullseye

	wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee "$KEYRING" >/dev/null
	gpg --no-default-keyring --keyring "$KEYRING" --list-keys

	echo "deb [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee /etc/apt/sources.list.d/nodesource.list
	echo "deb-src [signed-by=$KEYRING] https://deb.nodesource.com/$VERSION $DISTRO main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list

	sudo apt update && sudo apt install -y nodejs npm

	node --version
	npm --version
fi

DEB_GET_LOCATION=$HOME/.local/bin/deb-get
if [[ -e "$DEB_GET_LOCATION" ]]; then
	wget -c https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get -O "$DEB_GET_LOCATION"
	chmod +x "$DEB_GET_LOCATION"
fi
