#!/usr/bin/env bash

# Site: https://guix.gnu.org/

# * DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo guix wget bash)
s-checkdeps "${DEPS[@]}"

# * ENV VARS
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"

s-echo "GNU GUIX"

# INSTALLING
if [[ ! -x $(command -v guix) ]]; then
	wget "https://sv.gnu.org/people/viewgpg.php?user_id=127547" -qO - | sudo -i gpg --import -
	wget -P /tmp -c 'https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh'

	sudo bash /tmp/guix-install.sh
	sudo -i guix pull
	guix install glibc-locales 	# Fix GUIX_LOCPATH warning
fi

# UP TO DATE
guix pull
guix upgrade

