#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

DEPS=(systemctl)
s-checkdeps "${DEPS[@]}"

s-echo "Services"
sudo systemctl enable fstrim.timer

# pipewire
systemctl --user --now enable wireplumber pipewire pipewire-pulse

# autostart ssh agent
# systemctl --user --now enable ssh-agent.service
