#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(apt-get)
s-checkdeps "${DEPS[@]}"

INSTALL='sudo apt-get install -y'

lisp=(guile-3.0 chicken-bin libzstd-dev)
go=(golang golang-golang-x-tools)
pg=(postgresql postgresql-client postgresql-contrib libpq-dev)
langs_tools=(python3-pip)
mx=(emacs libgccjit0 libgccjit-12-dev libwebkit2gtk-4.0-dev libjansson-dev libjansson4)
tools=(jq git-email subversion mercurial libpq-dev editorconfig gnome-keyring direnv fd-find shfmt meson cmake)
editors=(zile vim neovim tidy ripgrep)

groups=("${mx[@]}"
    "${go[@]}"
    "${lisp[@]}"
    "${langs_tools[@]}"
    "${editors[@]}"
    "${pg[@]}"
    "${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist "$INSTALL" "$group"
done

if [[ ! $(command -v dbeaver) ]]; then
    [[ ! -f /tmp/dbeaver-ce_latest_amd64.deb ]] && wget -c "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb" -P /tmp
    sudo apt install -y /tmp/dbeaver-ce_latest_amd64.deb
fi

exit
