#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(apt-get bash)
s-checkdeps "${DEPS[@]}"

INSTALL='sudo dnf install -y'

langs_hobby=(guile)
langs_work=(java-17-openjdk java-17-openjdk-devel ruby-devel clang)
langs_tools=(maven ant)
editors=(zile vim neovim)
tools=(jq subversion mercurial direnv editorconfig fd-find tidy ripgrep shfmt git-email)

groups=("${langs_hobby[@]}"
    "${langs_work[@]}"
    "${langs_tools[@]}"
    "${editors[@]}"
    "${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist "$INSTALL" "$group"
done

exit
