#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

# * CHECKER
DEPS=(bash sudo apt dnf)
s-checkdeps "${DEPS[@]}"

# * SYSTEM
[[ -f /usr/bin/apt ]] && sudo apt update && sudo apt upgrade && sudo apt autoremove
[[ -f /usr/bin/dnf ]] && sudo dnf update && sudo dnf upgrade

# * FOREIGN
s-distro-guix
s-distro-flatpak
s-distro-misc
