#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt wget systemctl timedatectl fc-cache firewalld)
s-checkdeps "${DEPS[@]}"

REMOVE='sudo apt remove -y'
PURGE='sudo apt purge -y'
INSTALL='sudo apt-get install -y'

# =================================
s-echo "Foreign packages"

if [[ ! -x $(command -v flatpak) ]]; then
	$INSTALL flatpak gnome-software-plugin-flatpak
	sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi
