#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# TIP: gsettings list-recursively | grep WORD

# Debug Options
set -euo pipefail

# SWITCH
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"

gsettings set org.gnome.desktop.wm.keybindings cycle-windows "['<Super>z']"

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>b']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>f']"

# MOVE
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Super><Shift>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Super><Shift>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Super><Shift>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Super><Shift>4']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Super><Shift>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Super><Shift>6']"

# VOLUME
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-step 3
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up "['<Shift><Super>w']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down "['<Shift><Super>s']"
gsettings set org.gnome.settings-daemon.plugins.media-keys volume-mute "['<Shift><Super>e']"
gsettings set org.gnome.settings-daemon.plugins.media-keys mic-mute "['<Super>q']"

# MEDIA
gsettings set org.gnome.settings-daemon.plugins.media-keys next "['<Shift><Super>d']"
gsettings set org.gnome.settings-daemon.plugins.media-keys previous "['<Shift><Super>a']"
gsettings set org.gnome.settings-daemon.plugins.media-keys play "['<Alt><Super>e']"
gsettings set org.gnome.settings-daemon.plugins.media-keys previous "['<Alt><Super>a']"
gsettings set org.gnome.settings-daemon.plugins.media-keys next "['<Alt><Super>d']"

# SOUND
gsettings set org.gnome.desktop.wm.preferences audible-bell false
gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true
gsettings set org.gnome.desktop.sound event-sounds false
gsettings set org.gnome.rhythmbox.plugins.alternative_toolbar volume-control true

# gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-up "['<Alt><Super>w']"
# gsettings set org.gnome.settings-daemon.plugins.media-keys screen-brightness-down "['<Alt><Super>s']"

# THEMES
#gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
#gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.desktop.interface enable-animations false

# POWER
gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power power-button-action suspend
gsettings set org.gnome.desktop.lockdown disable-lock-screen true

# gsettings set org.gnome.settings-daemon.plugins.xrandr default-monitors-setup do-nothing

# MISC
gsettings set org.gnome.desktop.calendar show-weekdate true

gsettings set org.gnome.desktop.interface enable-hot-corners false
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-weekday true

gsettings set org.gnome.desktop.wm.preferences num-workspaces 5
gsettings set org.gnome.desktop.wm.preferences workspace-names "['emacs','read', 'term','www', 'media']"
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super>m']"
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['<Super>x']"
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super><Alt>f']"
gsettings set org.gnome.desktop.wm.keybindings close "['<Super><Alt>c']"
gsettings set org.gnome.desktop.wm.preferences auto-raise 'true'
gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'smart'
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false
gsettings set org.gnome.desktop.peripherals.mouse left-handed true
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

gsettings set org.gnome.shell.app-switcher current-workspace-only true

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true

#gsettings set org.gnome.system.locale region "pt_BR.UTF-8"

gsettings set org.gnome.desktop.input-sources mru-sources "[('xkb', 'br'), ('xkb', 'us')]"
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'br')]"

# APPS
gsettings set org.gnome.Evince.Default fullscreen 'true'
gsettings set org.gnome.Evince.Default show-sidebar 'false'
gsettings set org.gnome.Evince.Default show-toolbar 'false'

# EXTENSIONS
gsettings set org.gnome.shell.extensions.auto-move-windows application-list "['org.gnome.Evince.desktop:1', 'libreoffice-startcenter.desktop:1', 'libreoffice-writer.desktop:1', 'org.gnome.Terminal.desktop:3', 'firefox.desktop:4', 'mpv.desktop:5', 'foot.desktop:3', 'org.gnome.Rhythmbox3.desktop:5']"
gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'freon@UshakovVasilii_Github.yahoo.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com']"
