#!/usr/bin/env bash

s-echo "Post Install"

if [[ $(grep -rni '$HOME/.config/bash/config' "$HOME/.bashrc") ]]; then
    echo '[[ -f $HOME/.config/bash/config ]] && . "$HOME/.config/bash/config"' >>"$HOME/.bashrc"
fi

if [[ $(grep -rni '$HOME/.config/bash/aliases' "$HOME/.bashrc") ]]; then
    echo '[[ -f $HOME/.config/bash/aliases ]] && . "$HOME/.config/bash/aliases"' >>"$HOME/.bashrc"
fi

if [[ $(grep -rni '$HOME/.config/env_variables' "$HOME/.profile") ]]; then
    echo '[[ -x $HOME/.config/env_variables ]] && . "$HOME/.config/env_variables"' >>"$HOME/.profile"
fi

# default folders
mkdir -pv "$HOME"/{Downloads,Pictures,Documents,Videos,Builds,Projects,.local/bin,.config/scripts}

# silent parallel, for good.
parallel --citation

# cache all system fonts
sudo fc-cache -fv

# create or update the manual page index caches
sudo mandb

POSTGRES_VERSION=$(psql --version | awk '{print substr($3, 0, 2)}')
HBA_CONF="/etc/postgresql/$POSTGRES_VERSION/main/pg_hba.conf"
if ! sudo grep -i "$USER" "$HBA_CONF"; then
    sudo -u postgres createuser --createdb --createrole --pwprompt "$USER" # permission to create database and set password
    echo -n "local  all  all  md5" | sudo tee -a "$HBA_CONF"
    sudo systemctl restart postgresql
fi
