#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(sudo apt curl python3 go systemctl tee gpasswd)
s-checkdeps "${DEPS[@]}"

PARU_LOCATION="$HOME/Builds/paru"
[[ ! -d $PARU_LOCATION/.git ]] && git clone https://aur.archlinux.org/paru.git "$PARU_LOCATION"
git -C "$PARU_LOCATION" pull
cd "$PARU_LOCATION"
makepkg -si
