#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(apt-get bash)
s-checkdeps "${DEPS[@]}"

COMMAND='sudo apt-get install -y'

# EAMCS PACKAGES
# MX=(emacs libgccjit0 libgccjit-12-dev libwebkit2gtk-4.0-dev libjansson-dev libjansson4)
# s-dolist "$COMMAND" "${MX[@]}"

# PROGRAMMING LANGUAGES
LANGS_HOBBY=(libzstd-dev guile-3.0) # sbcl libssl-dev libfixposix-dev
s-dolist "$COMMAND" "${LANGS_HOBBY[@]}"

LANGS_WORK=(openjdk-17-jre openjdk-17-jdk)
s-dolist "$COMMAND" "${LANGS_WORK[@]}"

LANGS_TOOLS=(maven ant clang-format)
s-dolist "$COMMAND" "${LANGS_TOOLS[@]}"

# PROGRAMMING EDITORS
EDITORS=(zile vim neovim tidy ripgrep)
s-dolist "$COMMAND" "${EDITORS[@]}"

# PROGRAMMING TOOLS
TOOLS=(jq git-email subversion mercurial libpq-dev editorconfig gnome-keyring direnv fd-find)
s-dolist "$COMMAND" "${TOOLS[@]}"

exit
