#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo apt wget systemctl timedatectl fc-cache firewalld)
s-checkdeps "${DEPS[@]}"

REMOVE='sudo dnf remove -y'
PURGE='sudo dnf purge -y'
INSTALL='sudo dnf install -y'

# =================================
s-echo "Upgrading System"
sudo dnf upgrade -y

# =================================

s-echo "System Packages"

arch=()

gnu=(bash gcc make wget screen parallel gawk parted) # info recutils

system=(git openssh unzip zip p7zip at usbutils lsof atool time entr tree bc curl
	strace ltrace cpio lzop rsync pv texinfo autoconf automake socat tmux
	rpmbuild)

shell=(bash-completion ShellCheck fish)

fonts=(dejavu-fonts jetbrains-mono-fonts liberation-fonts google-noto-emoji-fonts)
# ttf-droid adobe-source-sans-fonts adobe-source-han-sans-otc-fonts

laptop=(acpi lm-sensors lshw libinput-tools)

wayland=(sway swaybg swaylock swayidle foot grim slurp wl-clipboard
	xorg-x11-server-Xwayland mako) #clipman

xorg=(xorg-x11-server-Xorg xorg-x11-xinit-session xclip xsel feh scrot
	network-manager-applet xautolock)

wm=(udiskie brightnessctl bluez blueman playerctl slock dmenu picom
	awesome zathura-cb zathura-pdf-mupdf zathura-djvu zathura-ps
	perl-File-MimeInfo)

laptop=(acpid lm_sensors) #tlp vainfo i965-va-driver libvdpau-va-gl1 libiw-dev hddtemp acpi-call dialog sysstat)

gtk=(atril cheese)

kde=(ktorrent kate falkon krita kdeconnectd kdevelop) # kdenlive

cli=(alacritty htop neofetch elinks libnotify ranger aria2)

user=(chromium firefox libreoffice gimp xdg-utils ImageMagick aspell aspell-pt
	aspell-en calibre pandoc inkscape discord telegram-desktop)

builds=(libX11-devel libXft-devel libXinerama-devel libXrandr-devel)

groups=("${arch[@]}"
	"${gnu[@]}"
	"${system[@]}"
	"${shell[@]}"
	"${wayland[@]}"
	"${xorg[@]}"
	"${sound[@]}"
	"${user[@]}"
	"${wm[@]}"
	"${builds[@]}"
	"${kde[@]}"
	"${gtk[@]}"
	"${cli[@]}"
	"${laptop[@]}"
	"${fonts[@]}")

for group in "${groups[@]}"; do
	s-dolist "$INSTALL" "$group"
done

# =================================
s-echo "Post Install"
mkdir -pv "$HOME"/{Downloads,Pictures,Documents,Videos,Builds,Projects,.local/bin}

s-echo "Distro Services"
sudo systemctl enable fstrim.timer
