#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(pacman)
s-checkdeps "${DEPS[@]}"

INSTALL='sudo pacman -S --noconfirm'

langs_hobby=(guile sbcl libfixposix) # libssl-dev libzstd-dev
langs_work=(jre17-openjdk jdk17-openjdk clang)
editors=(zile vim neovim)
tools=(jq subversion mercurial editorconfig-checker direnv fd tidy ripgrep shfmt) # libpq-dev git-email gnome-keyring

groups=("${langs_hobby[@]}"
    "${langs_work[@]}"
    "${editors[@]}"
    "${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist "$INSTALL" "$group"
done

exit
