#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG
set -euo pipefail

# TODO: Second argument set color, if none use default one

# * COLORS
RED="41m"
GREEN="42m"
PURPLE="45m"

# * Config
DEFAULT_COLOR=$RED

# * Arguments
MSG=$1
COLOR=$DEFAULT_COLOR

# * Run
echo
echo -e " \e[$COLOR $MSG \e[0m"
echo
