#!/usr/bin/env python3
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

from pathlib import Path
import argparse

import taglib


class Song:
    """Edit song attributes."""

    def __init__(self, song: str):
        self.song = taglib.File(song)

    def album(self, name: str) -> None:
        self.song.tags["ALBUM"] = name

    def artist(self, name: str) -> None:
        self.song.tags["ARTIST"] = name

    def title(self, name: str) -> None:
        self.song.tags["TITLE"] = name

    def date(self, name: str) -> None:
        self.song.tags["DATE"] = name

    def done(self):
        self.song.save()


# ACTIONS
# -----------------------------------------------------


def single(file: str) -> None:
    song = Song(str(file))

    if args.title:
        song.title(args.title)
    if args.artist:
        song.artist(args.artist)
    if args.album:
        song.album(args.album)
    if args.date:
        song.date(args.date)
    if song.modified:
        song.done()


def many(dir: str) -> None:
    for item in dir.iterdir():
        single(item)


# CLI
# -----------------------------------------------------

parser = argparse.ArgumentParser(
    prog="tagedit",
    description="Edit tag of file or directory files.",
    epilog="Praise the sun!",
)
parser.add_argument("-r", "--root", help="file/directory to edit")
parser.add_argument("-a", "--artist", help="artist name")
parser.add_argument("-t", "--title", help="song title")
parser.add_argument("-b", "--album", help="album title")
parser.add_argument("-d", "--date", help="album/song date of release")
args = parser.parse_args()

if args.root:
    root = Path(args.root)

    if root.is_dir():
        many(root)
    else:
        single(root)
else:
    parser.print_help()
    exit(1)

exit()
