#!/usr/bin/env bash

# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.

# DEBUG OPTIONS
set -euo pipefail

# Description: Play media given in system clipboard, or provided in terminal or replay last media.
PLAYER=mpv
LOG_FILE="$HOME/.config/scripts/videos"
URL="$(s-url)"

[[ ! -x $(command -v $PLAYER) ]] && echo "Player [ $PLAYER ] not found, exiting!" && exit

replay_last_media() {
    echo ">> Replaying last watched media"

    local last=$(tail -1 "$LOG_FILE")
    echo $last
    play "$last"
}

play() {
    log_url "$1"

    echo ">> playing $1"
    $PLAYER "$1"
}

log_url() {
    echo ">> logging url"
    echo -en "$1\n" >>"$LOG_FILE"
}

# PARSE CLI OPTIONS
OPTIONS=$(getopt --name play --options rhu: --longoptions replay,help,url: -- "$@")
eval set -- "$OPTIONS"
unset OPTIONS
while true; do
    case "$1" in
        -r | --replay)
            replay_last_media
            break
            ;;
        -u | --url)
            echo "Playing media with url: $2"
            play "$2"
            break
            ;;
        -h | --help)
            echo "Usage: play [ -l | --last ] [ -u | --url  URL ] [ -h | --help ]"
            break
            ;;
        *)
            play "$URL"
            break
            ;;
    esac
done

exit
