#!/usr/bin/env bash

# Debug Options
set -euo pipefail

# Description: Get video

DEPS=(yt-dlp ffmpeg)
s-checkdeps "${DEPS[@]}"

VIDEO_FOLDER="$HOME/Videos"
LOG_FOLDER="$HOME/.config/scripts"
URL="$(s-url)"
EXT='mp4'

# CREATE REQUIRED FOLDERS
[[ ! -d $VIDEO_FOLDER ]] && mkdir "$VIDEO_FOLDER"
[[ ! -d $LOG_FOLDER ]] && mkdir "$LOG_FOLDER"

cd "$VIDEO_FOLDER"

# GETTERS COMMANDS
declare -A YTDL
YTDL=([bin]='yt-dlp'
    [quality]='bestvideo+bestaudio'
    [format]="--format $EXT"
    [title]="-o %(title)s.f%(format_id)s.%(ext)s")

# LOG VIDEO URL
echo $URL >>"$LOG_FOLDER/videos"

# RUN
[[ -x $(command -v yt-dlp) ]] && ${YTDL[bin]} ${YTDL[format]} ${YTDL[title]} $URL && exit
