#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

# Description: Extract audio of video pointed in clipboards url.

# TODO: Check uri!

DEPS=(yt-dlp ffmpeg)
s-checkdeps "${DEPS[@]}"

FREE=(vorbis mp3)
EXT="${FREE[0]}"
URL="$(s-url)"
AUDIO_FOLDER="$HOME/Music/temp"
LOG_FOLDER="$HOME/.config/misc"

# CREATE REQUIRED FOLDERS
[[ ! -d $AUDIO_FOLDER ]] && mkdir "$AUDIO_FOLDER"
[[ ! -d $LOG_FOLDER ]] && mkdir "$LOG_FOLDER"
cd "$AUDIO_FOLDER"

# GETTERS COMMANDS
declare -A YTDL
YTDL=([bin]='yt-dlp'
      [format]='--extract-audio --audio-format'
      [title]="-o %(title)s.%(ext)s")

declare -A YOUTUBEDL
YOUTUBEDL=([bin]='youtube-dl'
      [format]='--extract-audio --audio-format'
      [title]="-o %(title)s.%(ext)s")

# OUTPUT INFO
INFO=$(
      cat <<EOF
Format: $EXT
URL: $URL
Folder: $AUDIO_FOLDER
EOF
)
echo "$INFO"

# LOG AUDIO URL
echo $URL >>"$LOG_FOLDER/audio"

# RUN
[[ -x $(command -v yt-dlp) ]] && ${YTDL[bin]} ${YTDL[format]} $EXT ${YTDL[title]} $URL && exit
[[ -x $(command -v youtube-dl) ]] && ${YOUTUBEDL[bin]} ${YOUTUBEDL[audio]} "$EXT" ${YOUTUBEDL[title]} "$URL" && exit
