#!/usr/bin/env bash

# Debug Options
set -euo pipefail

# Description: Play media given in system clipboard, or provided in terminal or replay last media.
# DEPS=(vlc mpv getopt)

PLAYERS=(mpv vlc)
CLIPBOARD_URL="$(s-url)"

# Log last required media url
LOG_FILE="$HOME/.config/scripts/play"
echo "$CLIPBOARD_URL" >>"$LOG_FILE"

# TODO properly check for players, and set first player found as default player or exit : for player in
if [[ ! -x $(command -v mpv) ]] || [[ ! -x $(command -v vlc) ]]; then
    echo "No supported player is available \[ ${PLAYERS[@]} \]"
    exit
fi

PLAYER=mpv

# Play media found in clipboard url if no argument is given
if [[ $# -eq 0 ]]; then
    $PLAYER "$CLIPBOARD_URL" && exit 1
    exit 1
fi

replay_last_media() {
    echo "Replaying last watched media"
    local last=$(tail -1 "$LOG_FILE")
    $PLAYER "$last"
    exit
}

# Parse options
options=$(getopt --name play --options lhu: --longoptions last,help,url: -- "$@")
eval set -- "$options"

# Run per options given
while true; do
    case "$1" in
        -l | --last)
            replay_last_media
            break
            ;;
        -u | --url)
            echo "Playing media in inline url: $2"
            # $PLAYER "$2"
            break
            ;;
        -h | --help)
            echo "Usage: play [ -l | --last ] [ -u | --url  URL ] [ -h | --help ]"
            break
            ;;
    esac
done

exit
