#!/usr/bin/env bash

# Debug Options
set -euo pipefail

# Description:
# Deps: youtube-dl, ffmpeg

URL="$(s-url)"
LOG_FOLDER="$HOME/.config/misc"

# LOG VIDEO URL
echo "$URL" >>"$LOG_FOLDER/play"

[[ -x $(command -v mpv) ]] && mpv "$URL"
