#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

# Description: Extract audio of video pointed in clipboards url.

# TODO: Check uri!

DEPS=(yt-dlp ffmpeg)
s-checkdeps "${DEPS[@]}"

FREE=(vorbis mp3)
EXT="${FREE[0]}"
URL="$(s-url)"
FOLDER="$HOME/Music/temp"

cd "$FOLDER"

# GETTERS ATTRIBUTES
declare -A YTDL
YTDL=([bin]='yt-dlp'
      [audio]='--extract-audio --audio-format'
      [title]="-o '%(title)s.%(ext)s'")

declare -A YOUTUBEDL
YOUTUBEDL=([bin]='youtube-dl'
      [audio]='--extract-audio --audio-format'
      [title]="-o '%(title)s.%(ext)s'")

# RUN
echo <<EOF
Format: $EXT
URL: $URL
Folder: $FOLDER
EOF

[[ -x $(youtube-dl) ]] && ${YOUTUBEDL[bin]} ${YOUTUBEDL[audio]} "$EXT" ${YOUTUBEDL[title]} "$URL" && exit
[[ -x $(yt-dlp) ]] && ${YTDL[bin]} ${YTDL[audio]} "$EXT" ${YTDL[title]} "$URL" && exit
