#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

# Description: Get video

DEPS=(yt-dlp ffmpeg)
s-checkdeps "${DEPS[@]}"

VIDEO_FOLDER="$HOME/Videos"
LOG_FOLDER="$HOME/.config/scripts"
URL="$(s-url)"
EXT='mp4'

# CREATE REQUIRED FOLDERS
[[ ! -d $VIDEO_FOLDER ]] && mkdir "$VIDEO_FOLDER"
[[ ! -d $LOG_FOLDER ]] && mkdir "$LOG_FOLDER"

cd "$VIDEO_FOLDER"

# GETTERS COMMANDS
declare -A YTDL
YTDL=([bin]='yt-dlp'
    [quality]='bestvideo+bestaudio'
    [format]="--format $EXT"
    [title]="--trim-filenames 30 -o %(title)s.f%(format_id)s.%(ext)s")

# LOG VIDEO URL
echo $URL >>"$LOG_FOLDER/videos"

# RUN
[[ -x $(command -v yt-dlp) ]] && ${YTDL[bin]} --restrict-filenames ${YTDL[format]} ${YTDL[title]} $URL && exit
