#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(pip)
s-checkdeps "${DEPS[@]}"

# AWS ELASTIC BEAN
[[ ! -x $(command -v eb) ]] && pip install awsebcli --upgrade --user

# AWS IAM AUTHENTICATOR
if [[ ! -x $(command -v aws-iam-authenticator) ]]; then
    curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator -P "$HOME/.local/bin"
    chmod +x "$HOME/.local/bin/aws-iam-authenticator"
fi

if [[ ! -x $(command -v podman-compose) ]]; then
    python3 -m pip install podman-compose --upgrade

    # Docker Compose will use the correct socket.
    export DOCKER_HOST=///run/user/$UID/podman/podman.sock
fi

if [[ ! -x $(command -v eksctl) ]]; then
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    sudo mv /tmp/eksctl /usr/local/bin
fi

if [[ ! -x $(command -v k3s) ]]; then
    ''
fi

[[ ! -x $(command -v kind) ]] && GO111MODULE=on go install sigs.k8s.io/kind@v0.12.0
