#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(sudo podman)
s-checkdeps "${DEPS[@]}"

PULL='podman pull'
REGISTRY='docker.io/library'

stable=(node:16-alpine mongo:6 postgres:15-alpine)
distro=(debian:bullseye)

all=("${stable[@]}"
    "${latest[@]}"
    "${distro[@]}")

for image in "${all[@]}"; do
    s-dolist "$PULL" "$REGISTRY/$image"
done

exit
# docker images | grep -v REPOSITORY | awk 'BEGIN{OFS=":"} {print $1,$2}' | xargs -L1 docker pull
