#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

# * CHECKER
DEPS=(bash minikube k3s)
s-checkdeps "${DEPS[@]}"

# PODMAN
systemctl --user enable --now podman.socket
XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
export DOCKER_SOCK=$XDG_RUNTIME_DIR/podman/podman.sock

# MINIKUBE

minikube config set driver podman
minikube config set rootless true

# minikube start --driver=podman --container-runtime=containerd

# K3S

[[ ! -x $(command -v k3s) ]] && curl -sfL https://get.k3s.io | sh -

K3S_KUBECONFIG=$HOME/.local/k3s-kube-config
if [[ ! -f "$K3S_KUBECONFIG" ]]; then
    sudo k3s kubectl config view --raw >"$K3S_KUBECONFIG"
    chmod 0600 "$K3S_KUBECONFIG"
    # set to KUBECONFIG="$K3S_KUBECONFIG"
fi

# Check for Ready node, takes ~30 seconds
# k3s kubectl get node

# K3D
wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
