#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(sudo podman)
s-checkdeps "${DEPS[@]}"

PULL='podman pull'
REGISTRY='docker.io/library/'

stable=(openjdk:17-jdk maven:3-eclipse-temurin-17 ruby:3 postgres:14 mysql:8 redis:7)
latest=(openjdk:19-jdk) # maven:3-eclipse-temurin-19
distro=(debian:bullseye ubuntu:22.04)

groups=("${stable[@]}"
    "${latest[@]}"
    "${distro[@]}")

for group in "${groups[@]}"; do
    s-dolist "$PULL" "$group"
done

# docker images | grep -v REPOSITORY | awk 'BEGIN{OFS=":"} {print $1,$2}' | xargs -L1 docker pull
