#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(sudo podman)
s-checkdeps "${DEPS[@]}"

PULL='podman pull'
REGISTRY='docker.io/library/'

stable=(openjdk:17-jdk openjdk:17-jdk ruby:3 node:16 postgres:14 mysql:8 ruby:3 redis:7)
small=(openjdk:17-jdk-alpine ruby:3-alpine node:16-alpine postgres:14-alpine redis:7-alpine)
latest=(openjdk:19-jdk)
distro=(debian:bullseye ubuntu:22.04 fedora:36)

groups=("${stable[@]}"
    "${latest[@]}"
    "${distro[@]}"
    "${small[@]}")

for group in "${groups[@]}"; do
    s-dolist "$PULL" "$group"
done

# docker images | grep -v REPOSITORY | awk 'BEGIN{OFS=":"} {print $1,$2}' | xargs -L1 docker pull
