#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(vagrant)
s-checkdeps "${DEPS[@]}"

[[ ! -x $(command -v vagrant) ]] && echo 'Vagrant is not installed!' && return

boxes=(debian/bullseye64 ubuntu/focal64)

[[ ! "$(vagrant box list | grep debian)" ]] && s-dolist 'vagrant box add' "${boxes[@]}"
s-dolist 'vagrant box update' "${boxes[@]}"
