#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(pip)
s-checkdeps "${DEPS[@]}"

# AWS ELASTIC BEAN
[[ ! -x $(command -v eb) ]] && pip install awsebcli --upgrade --user

# AWS IAM AUTHENTICATOR
if [[ ! -x $(command -v aws-iam-authenticator) ]]; then
    curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator -P "$HOME/.local/bin"
    chmod +x "$HOME/.local/bin/aws-iam-authenticator"
fi
