#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(perl cpan)
s-checkdeps "${DEPS[@]}"

# automate CPAN initial configuration
(
    echo y
    echo o conf prerequisites_policy follow
    echo o conf commit
) | cpan

# CPNAM
cpan App::cpanminus

# Modules
cpanm --self-upgrade Audio::TagLib
