#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(python bash)
s-checkdeps "${DEPS[@]}"

tools=(black pipenv pyflakes pytest isort nose pyperclip)
libs=(beautifulsoup4 interval)
apps=(cryptography conan)

groups=("${tools[@]}" "${libs[@]}" "${apps[@]}")

COMMAND="python3 -m pip install --upgrade --user --break-system-packages"
for group in "${groups[@]}"; do
    s-dolist "$COMMAND" "${group[@]}"
done
