#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(curl)
s-checkdeps "${DEPS[@]}"

# CARGO
. "$HOME/.cargo/env"

tools=(starship)
tasks=(cargo-watch cargo-tarpaulin)
apps=(fd-find ripgrep exa bat procs sd du-dust tokei)

groups=("${tools[@]}" "${tasks[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist 'cargo install --locked' "$group"
done

# RUSTUP
tools=(rust-analyzer clippy rustfmt cargo-audit)

groups=("${tools[@]}")

for group in "${groups[@]}"; do
    s-dolist 'rustup component add' "$group"
done

# RUST ANALYZER
ln -sf "$(rustup which --toolchain stable rust-analyzer)" "$HOME/.local/bin/rust-analyzer"

exit
