#!/usr/bin/env bash

# * Debug Options
set -euo pipefail

DEPS=(sudo guix wget bash)
s-checkdeps "${DEPS[@]}"
COMMAND="guix install"

guix pull
guix package -u

packages=(nss-certs font-dejavu)
apps=(haunt guile-hall akku)
langs=(guile guile-readline sbcl)

all=("${packages[@]}" "${apps[@]}" "${langs[@]}")

for single in "${all[@]}"; do
	s-dolist "$COMMAND" "${all[@]}"
done
