#!/usr/bin/env bash

# * Debug Options
set -euo pipefail

DEPS=(sudo guix bash)
s-checkdeps "${DEPS[@]}"

frame=("laravel/installer")
tools=("phpunit/phpunit" "phing/phing" "friendsofphp/php-cs-fixer" "phpdocumentor/phpdocumentor" "squizlabs/php_codesniffer=*")

all=("${frame[@]}" "${tools[@]}")
for each in "${all[@]}"; do
    s-echo "-> $each"
    [[ ! -x $(command -v "$each") ]] && composer global require --no-interaction "$each"
done

# UPDATE ALL
composer global update
