#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(ruby gem)
s-checkdeps "${DEPS[@]}"

essential=(bundler rake)
tools=(ruby-lsp reek rufo rubocop pry taglib-ruby) # solargraph

all=("${essential[@]}" "${tools[@]}")

for i in "${all[@]}"; do
    s-echo "-> $i"

    [[ ! -x $(command -v $i) ]] && gem install $i
    gem update $i
done
