#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(npm)
s-checkdeps "${DEPS[@]}"

[[ ! -x $HOME/.bun/bin/bun ]] && curl https://bun.sh/install | bash

essential=(npm) # yarn
tools=(stylelint js-beautify prettier)
node=(nodemon)
ts=(typescript)
ts_tools=(ts-node typescript-language-server)

all=("${essential[@]}" "${tools[@]}" "${node[@]}" "${ts[@]}")

for single in "${all[@]}"; do
	s-dolist 'npm install --global' "$single"
done

# Update all packages
npm update --global

exit 0

# [[ ! -x $HOME/.deno/bin/deno ]] && curl -fsSL https://deno.land/install.sh | bash
