#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(perl cpan)
s-checkdeps "${DEPS[@]}"

# Automate CPAN initial configuration
# ----------------------------------------------
if [[ ! -f $HOME/.cpan/CPAN/MyConfig.pm ]]; then
    (
        echo y
        echo o conf prerequisites_policy follow
        echo o conf commit
    ) | cpan
fi

# CPNAM
# ----------------------------------------------
[[ ! -f $HOME/perl5/bin/cpanm ]] && cpan App::cpanminus && cpanm --version

# MODULES
# ----------------------------------------------
tools=(Perl::LanguageServer)
libs=(Audio::TagLib)

all=("${tools[@]}" "${libs[@]}")

for pack in "${all[@]}"; do
    s-echo "$pack"
    cpanm --self-upgrade "$pack"
done
