#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(go)
s-checkdeps "${DEPS[@]}"

s-echo "Golang Toolings."

COMMAND='go install -v'

lsp=('github.com/hashicorp/terraform-ls@latest' 'golang.org/x/tools/gopls@latest')
apps=('github.com/xxxserxxx/gotop/v4/cmd/gotop@latest' 'github.com/antonmedv/llama@latest')
tools=('github.com/fatih/gomodifytags@latest'
	'github.com/x-motemen/gore/cmd/gore@latest'
	'github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest'
	'github.com/ramya-rao-a/go-outline@latest'
	'github.com/go-delve/delve/cmd/dlv@latest'
	'github.com/cweill/gotests/...@latest'
	'github.com/ramya-rao-a/go-outline@latest'
	'github.com/mdempsky/gocode@latest'
	'github.com/githubnemo/CompileDaemon@latest'
	'golang.org/x/tools/cmd/guru@latest')
devel=('mvdan.cc/sh/v3/cmd/shfmt@latest'
	'github.com/x-motemen/gore/cmd/gore@latest'
	'github.com/erning/gorun@latest')

groups=("${lsp[@]}" "${tools[@]}" "${apps[@]}" "${devel[@]}")

for group in "${groups[@]}"; do
	s-dolist "$COMMAND" "$group"
done
