#!/usr/bin/env bash

# Debug Options
set -euo pipefail

DEPS=(python bash)
s-checkdeps "${DEPS[@]}"

COMMAND="python3 -m pip install --upgrade"

tools=(black pipenv pyflakes pytest isort nose pyperclip)
libs=(beautifulsoup4 interval)
apps=(cryptography conan)

groups=("${tools[@]}" "${libs[@]}" "${apps[@]}")

for group in "${groups[@]}"; do
    s-dolist "$COMMAND" "${group[@]}"
done
