#!/usr/bin/env bash

# * Debug Options
set -euo pipefail

DEPS=(sudo guix bash)
s-checkdeps "${DEPS[@]}"

frame=("laravel/installer")
tools=("psy/psysh" "phpunit/phpunit" "phing/phing" "friendsofphp/php-cs-fixer" "squizlabs/php_codesniffer=*") # "phpdocumentor/phpdocumentor"

all=("${frame[@]}" "${tools[@]}")
for each in "${all[@]}"; do
    s-echo "-> $each"
    composer global require --no-interaction "$each"
done

# UPDATE ALL
composer global update
