#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG
set -euo pipefail

# TODO
# - check if usb stick is plugged on.

s-echo "USB Tasks"

ARCHIVED="$HOME/Downloads/archived"
DISTRO="$(awk '/^NAME=/ { split($0,a,"="); print a[2] }' /etc/os-release)"
USB_NAME="MACHO"
USB=""

case $DISTRO in
    "NixOS" | "Arch Linux" | "Manjaro")
        USB="/run/media"
        ;;
    "Debian GNU/Linux" | "Fedora")
        USB="/media"
        ;;
esac

mkdir -pv "$ARCHIVED"
find "$ARCHIVED" -name "*.tar" | parallel --max-args=1 cp -rpv "{1}" "$USB/$USER/$USB_NAME/dots"

# LEGACY
# "$(grep '^NAME=' /etc/os-release | cut -f2 -d"=" | tr -d '"')"
