#!/usr/bin/env ruby
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# frozen_string_literal: true

# Symlink partition folders to $HOME
class Homey
  IGNORE_THESE = %w[.Trash-1000 lost+found].freeze

  attr_reader :root, :target_link

  def initialize(root)
    @root = root
  end

  # Confirms if root is a folder or return w/ exeception
  def root_exist?
    Pathname.new root.exist?
  end

  def folders_found
    folders_found = {}
    home = Pathname.new Dir.home

    root.each_child do |folder|
      next if IGNORE_THESE.include? folder.basename.to_s

      folders_found[folder] = home.join folder.basename
    end

    folders_found
  end

  # Remove $HOME folders found in partition
  def cleanup_home
    target_link.each_key do |link_name|
      link_name.delete if link_name.exist?
    end
  end

  def symlink_folders
    target_link.each do |target, link_name|
      File.symlink target, link_name
    end
  end

  def run
    unless root_exist?
      print "No such a directory '#{root}' exist! Exiting."
      exit!
    end

    @root = Pathname root
    @target_link = folders_found

    cleanup_home
    symlink_folders
  end

  public :run
end

# RUN
Homey.new(ARGV.first).run
