#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

git config --global init.defaultBranch main

git config --global user.name "$USER"
git config --global user.email "$USER@outlook.com"

git config --global core.editor "nano -Sxmkcig_"
git config --global core.autocrlf "input"

git config --global color.ui true

git config --global credential.helper cache

git config --global pull.ff only

git config --global fetch.prune true
