#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

# REGISTER USER
EMAIL="$USER@outlook.com"
SSH_HOME="$HOME/.ssh"
SSH_KEY="$SSH_HOME/.ssh/id_ed25519"

# GENERATE NEW KEY
[[ ! -f $SSH_KEY ]] && ssh-keygen -t ed25519 -C "$EMAIL"

if [[ ! -f "$SSH_HOME/config" ]]; then
  cat <<EOF >>"$SSH_HOME/config"
Host *
     AddKeysToAgent yes
     IdentityFile id_ed25519
EOF
fi

# PROTECT FILES
chmod 700 "$SSH_HOME"
chmod 400 "$SSH_KEY"
chmod 600 "$SSH_HOME/known_hosts"

exit

# NEW GLOBAL DEFAULTS
# sudo sed -i "s/Port 22|Port 33/g" # new port
# sudo sed -i "PermitRootLogin no"  # Disable root
# sudo sed -i "AllowUsers username" # limit users acess
# sudo sed -i "Protocol 2"          # use protocol 2
