#!/usr/bin/env bash

# Debug Options
set -euo pipefail

# REGISTER USER
EMAIL="$USER@outlook.com"
SSH_HOME="$HOME/.ssh"
SSH_KEY="$SSH_HOME/.ssh/id_ed25519"

# GENERATE NEW KEY
[[ ! -f $SSH_KEY ]] && ssh-keygen -t ed25519 -C "$EMAIL"

[[ ! -f "$SSH_HOME/config" ]] && cat <<EOF >>"$SSH_HOME/config"
Host *
     AddKeysToAgent yes
     IdentityFile id_ed25519
EOF

# PROTECT FILES
chmod 700 "$SSH_HOME"
chmod 400 "$SSH_KEYS"
chmod 600 "$SSH_HOME/known_hosts"

exit

# NEW GLOBAL DEFAULTS
# sudo sed -i "s/Port 22|Port 33/g" # new port
# sudo sed -i "PermitRootLogin no"  # Disable root
# sudo sed -i "AllowUsers username" # limit users acess
# sudo sed -i "Protocol 2"          # use protocol 2
