#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

URL=""

[[ $XDG_SESSION_TYPE = "x11" ]] && URL=$(xclip -selection clipboard -o)
[[ $XDG_SESSION_TYPE = "wayland" ]] && URL=$(wl-paste)
[[ $(command -v wl-paste) ]] && URL=$(wl-paste)

if [[ ! "$URL" =~ http?(s)://* ]]; then
    echo 'ERROR: Text found in clipboard is not a proper URI'
    exit 1
else
    printf "%s" "$URL"
fi
