#!/usr/bin/env bash

# DEBUG OPTIONS
set -euo pipefail

[[ $XDG_SESSION_TYPE = "x11" ]] && URL=$(xclip -selection clipboard -o)
[[ $XDG_SESSION_TYPE = "wayland" ]] && URL=$(wl-paste)

printf "%s" "$URL"
