#!/usr/bin/env bash

# DEBUG SETTINGS
set -euo pipefail

TO=/media/$USER/MOAR

# * CHECKER
DEPS=(rsync qas cp)
s-checkdeps "${DEPS[@]}"

# Save last state to usb-stick
if [[ -x $(command -v qas) ]]; then
    qas --grab
    qas --archive bin,lar,annotations # TODO: save to usb-stick

    rsync -vhazrtP "$HOME/Downloads/archived" "$TO"
fi

# * USB-TO
rsync -vhazrtP --ignore-existing --exclude={'.terraform','.vagrant','node_modules','.local','.git'} /da/personal "$TO"
rsync -vhazrtP --ignore-existing --exclude={'.terraform','.vagrant','node_modules','.local','.git'} /da/work "$TO"
rsync -vhazrtP --ignore-existing /da/livros "$TO"
rsync -vhazrtP --ignore-existing /da/misc "/media/$USER/MOAR/"
rsync -vhazrtP --ignore-existing /da/pictures "$TO"
