#!/usr/bin/env bash

# Description: auto-start some software executables

DEPS=(bash command nohup pgrep awk nm-applet blueman udiskie mpd firefox okular)
LOCAL_BIN="$HOME/.local/bin"

# ===================================================
# * LIST OF PROGRAMS
TOOLS=('blueman-applet'
  "nm-applet --indicator"
  'udiskie --notify --tray')

APPS=("$LOCAL_BIN/s-run-emacs"
  'mpd'
  's-wm-wall'
  'okular'
  'insomnia'
  'firefox')

WAYLAND=('foot')

# ===================================================
# * HELPERS

not_found() {
  # type: boolean
  # check if program executable is found

  local app=$(echo "$1" | awk '{ print $1}') # get first word of command string with options given

  [[ ! -x $(command -v "$app") ]]
}

is_running() {
  # type: boolean
  # return if PROGRAM is running

  [[ $(pgrep -f "$1") ]]
}

run() {
  # type: void
  # run program as gnu bash background process

  nohup bash -c "$1" &
}

dolist() {
  # type: void
  # given a list of programs, perform a few tasks before running.

  local apps=("$@")

  for app in "${apps[@]}"; do
    not_found "$app" && continue
    is_running "$app" && continue
    run "$app"
  done
}

# ===================================================
# * RUN

dolist "${TOOLS[@]}"
dolist "${APPS[@]}"
dolist "${WAYLAND[@]}"
