#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Description: auto-start some software executables

DEPS=(bash command nohup pgrep awk nm-applet blueman udiskie mpd firefox okular)
LOCAL_BIN="$HOME/.local/bin"

# ===================================================
# * LIST OF PROGRAMS
TOOLS=('blueman-applet'
  "nm-applet --indicator"
  'udiskie --notify --tray',
  "mako")

APPS=("$LOCAL_BIN/s-run-emacs"
  'mpd'
  'firefox')

WAYLAND=('foot')

# ===================================================
# * HELPERS

not_found() {
  # type: boolean
  # check if program executable is found

  local app=$(echo "$1" | awk '{ print $1}') # get first word of command string with options given

  [[ ! -x $(command -v "$app") ]]
}

is_running() {
  # type: boolean
  # return if PROGRAM is running

  [[ $(pgrep -f "$1") ]]
}

run() {
  # type: void
  # run program as gnu bash background process

  nohup bash -c "$1" &
}

dolist() {
  # type: void
  # given a list of programs, perform a few tasks before running.

  local apps=("$@")

  for app in "${apps[@]}"; do
    not_found "$app" && continue
    is_running "$app" && continue
    run "$app"
  done
}

# ===================================================
# * RUN

dolist "${TOOLS[@]}"
dolist "${APPS[@]}"
dolist "${WAYLAND[@]}"
