#!/usr/bin/env bash

FOLDER="$HOME/Pictures/wallpapers/"
WALL="$(find "$FOLDER" -type f | shuf -n 1)"

cat <<EOF
Folder: $FOLDER
Wallpaper: $WALL
EOF

[[ $XDG_SESSION_TYPE = 'wayland' ]] && swaybg -m fit -i "$WALL" && exit
[[ $XDG_SESSION_TYPE = 'Xorg' ]] && feh --bg-max "$WALL" && exit
