#!/usr/bin/env bash

FOLDER="$HOME/Pictures/wallpapers/"
WALL="$(find "$FOLDER" -type f | shuf -n 1)"

cat <<EOF
Folder: $FOLDER
Wallpaper: $WALL
EOF

if [[ $XDG_SESSION_TYPE = 'wayland' ]]; then
    swaybg -m fit -i "$WALL"  &
    exit
fi

if [[ $XDG_SESSION_TYPE = 'Xorg' ]]; then
    feh --bg-max "$WALL" & 
    exit
fi
