#!/usr/bin/env bash

deps=(nmcli iwd sudo curl)
s-checkdeps "${deps[@]}"

if [[ $(pgrep -x NetworkManager) ]]; then
    state="$(nmcli connection show | awk 'NR==2 {print $4}')"
    ssid='barbosas5g' # "$(nmcli connection show | awk 'NR==2 {print $1}')"

    [[ $state == '--' ]] && nmcli con up "$ssid" || nmcli con down "$ssid"
fi

# device=$(ip a | awk '/wl+/ { split($0,a,": "); print a[2] }')
# [[ ! $(pgrep -x iwd) && ! $(curl -I gnu.org) ]] && sudo ifup "$DEVICE" || sudo ifdown "$DEVICE"
