#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(curl bash)
s_checkdeps "${DEPS[@]}"

DOTNET_DIR="$HOME/.dotnet"
DOTNET_BIN_NAME=dotnet-install
DOTNET_INSTALL_BIN="$HOME/.local/bin/$DOTNET_BIN_NAME"
DOTNET_VERSION=8.0

if [[ ! -f $DOTNET_INSTALL_BIN ]]; then
    wget https://dot.net/v1/dotnet-install.sh -O "$DOTNET_INSTALL_BIN"
    chmod +x "$DOTNET_INSTALL_BIN"
fi

[[ -f $DOTNET_INSTALL_BIN ]] && $DOTNET_INSTALL_BIN --channel "$DOTNET_VERSION"
[[ -f $DOTNET_INSTALL_BIN ]] && $DOTNET_INSTALL_BIN --runtime dotnet --version 6.0.31
[[ -f $DOTNET_DIR/dotnet ]] && ln -sf "$DOTNET_DIR/dotnet" "$HOME/.local/bin/dotnet"
