#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(ruby)
s_checkdeps "${DEPS[@]}"

RBENV_HOME="$HOME/.rbenv"

[[ ! -d $RBENV_HOME/.git ]] && \
    git clone --single-branch --depth=10 https://github.com/rbenv/rbenv.git "$RBENV_HOME"
[[ ! -d $RBENV_HOME/plugins/ruby-build/.git ]] && \
    git clone --single-branch --depth=10 https://github.com/rbenv/ruby-build.git "$RBENV_HOME/plugins/ruby-build"

"$RBENV_HOME/bin/rbenv" init
