#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

DEPS=(git dart flutter)
s_checkdeps "${DEPS[@]}"

LOCAL_DIR=$HOME/.local
FLUTTER_DIR="$LOCAL_DIR/flutter"

[[ ! -d $FLUTTER_DIR/.git ]] && git clone https://github.com/flutter/flutter --branch stable --single-branch "$FLUTTER_DIR"

ln -sf "$FLUTTER_DIR"/bin/flutter "$LOCAL_DIR/bin"
ln -sf "$FLUTTER_DIR"/bin/dart "$LOCAL_DIR/bin"

git -C "$FLUTTER_DIR" pull
