#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo dnf)
s_checkdeps "${DEPS[@]}"

INSTALL='sudo dnf install -y'

# =================================
s_echo "Upgrading System"
sudo dnf upgrade -y

# =================================

s_echo "System Packages"

fedora=()
gnu=(bash gcc make wget screen parallel gawk parted) # info recutils
system=(git openssh unzip zip p7zip at usbutils lsof atool time entr tree bc curl strace ltrace cpio lzop rsync pv texinfo autoconf automake socat tmux rpmbuild)
shell=(bash-completion ShellCheck fish)
fonts=(dejavu-fonts jetbrains-mono-fonts liberation-fonts google-noto-emoji-fonts) # ttf-droid adobe-source-sans-fonts adobe-source-han-sans-otc-fonts
laptop=(acpi lm-sensors lshw libinput-tools)
wayland=(sway swaybg swaylock swayidle foot grim slurp wl-clipboard xorg-x11-server-Xwayland mako) #clipman
xorg=(xorg-x11-server-Xorg xorg-x11-xinit-session xclip xsel feh scrot network-manager-applet xautolock)
wm=(udiskie brightnessctl bluez blueman playerctl slock dmenu awesome zathura-cb zathura-pdf-mupdf zathura-djvu zathura-ps perl-File-MimeInfo)
laptop=(acpid lm_sensors) #tlp vainfo i965-va-driver libvdpau-va-gl1 libiw-dev hddtemp acpi-call dialog sysstat)
gtk=(atril cheese)
kde=(ktorrent kate falkon krita kdeconnectd kdevelop) # kdenlive
cli=(alacritty htop neofetch elinks libnotify ranger aria2)
user=(chromium firefox libreoffice gimp xdg-utils ImageMagick aspell aspell-pt aspell-en calibre pandoc inkscape discord telegram-desktop pavucontrol)
builds=(libX11-devel libXft-devel libXinerama-devel libXrandr-devel)

groups=("${arch[@]}"
	"${gnu[@]}"
	"${system[@]}"
	"${shell[@]}"
	"${wayland[@]}"
	"${xorg[@]}"
	"${sound[@]}"
	"${user[@]}"
	"${wm[@]}"
	"${builds[@]}"
	"${kde[@]}"
	"${gtk[@]}"
	"${cli[@]}"
	"${laptop[@]}"
	"${fonts[@]}")

for group in "${groups[@]}"; do
	s-dolist "$INSTALL" "$group"
done
