#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

DEPS=(sudo dnf)
s_checkdeps "${DEPS[@]}"

sudo dnf install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(
        rpm -E
        %fedora
    ).noarch.rpm
sudo dnf install \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(
        rpm
        -E %fedora
    ).noarch.rpm
sudo dnf groupupdate multimedia --setop="install_weak_deps=False" \
    --exclude=PackageKit-gstreamer-plugin
sudo dnf groupupdate sound-and-video

INSTALL=sudo dnf install -y

media=(mpv ffmpeg mpc mpd ncmpcpp)
sound=(pipewire pipewire-pulse lib32-pipewire pipewire-docs) # wireplumber pulseaudio-utils
groups=("${media[@]}" "${sound[@]}")

for group in "${groups[@]}"; do
    s_dolist "$INSTALL" "$group"
done

exit
