#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

# Description: Get given in system clipboard, or provided in terminal or replay last media.
# DEPS=(wget curl)

# GETTERS
declare -A WGET
WGET=([bin]='wget'
    [options]='-c -P')

declare -A CURL
CURL=([bin]='curl'
    [options]='')

# CONFIG
# GETTERS=("${WGET[@]}" "${CURL[@]}") # merge all arrays

CLIPBOARD_URL="$(s_url)"
FOLDER=$HOME/Pictures/temp

# CHECKER
[[ -z $CLIPBOARD_URL ]] && echo 'clipboard has no url, exiting!' && return

# LOG
# Log last required media url
LOG_FILE="$HOME/.config/scripts/pic"
echo "$CLIPBOARD_URL" >>"$LOG_FILE"

# declare -A GETTER
declare -n GETTER=WGET
COMMAND="${GETTER[bin]} ${GETTER[options]} $FOLDER $CLIPBOARD_URL"

# RUN
echo "getter: ${GETTER[bin]}
url: $CLIPBOARD_URL
folder: $FOLDER"

echo "command:  $COMMAND"

mkdir -p $FOLDER
exec $COMMAND
