#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

# Description: Get video

DEPS=(yt-dlp ffmpeg)
s_checkdeps "${DEPS[@]}"

VIDEO_FOLDER="$HOME/Videos"
LOG_FOLDER="$HOME/.config/scripts"
URL="$(s_url)"
EXT='mp4'
TITLE_LENGTH=120

# CREATE REQUIRED FOLDERS
[[ ! -d $VIDEO_FOLDER ]] && mkdir "$VIDEO_FOLDER"
[[ ! -d $LOG_FOLDER ]] && mkdir "$LOG_FOLDER"

cd "$VIDEO_FOLDER"

# GETTERS COMMANDS
declare -A YTDL
YTDL=([bin]='yt-dlp'
    [quality]='-f "bestvideo[height<=1080]+bestaudio/best[height<=1080]"'
    [format]="--format $EXT"
    [options]="--ignore-config --restrict-filenames --trim-filenames $TITLE_LENGTH -wc"
    [title]="--output %(title)s.f%(format_id)s.%(ext)s")

# LOG VIDEO URL
echo $URL >>"$LOG_FOLDER/videos"

# RUN
[[ -x $(command -v yt-dlp) ]] && ${YTDL[bin]} ${YTDL[quality]} ${YTDL[options]} ${YTDL[format]} ${YTDL[title]} $URL && exit
