#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# ===========================
# QUICKLISP INSTALL

QUICKLISP=quicklisp.lisp
QUICKLISP_LOCATION="/tmp/$QUICKLISP"
[[ ! -f $QUICKLISP_LOCATION ]] && wget -c https://beta.quicklisp.org/quicklisp.lisp -P /tmp

# ===========================
# STUMPWM INSTALL

if [[ ! -f "$HOME/quicklisp/dists/quicklisp/installed/releases/dbus.txt" ]]; then
        sbcl --no-sysinit --no-userinit --load /tmp/quicklisp.lisp \
                --eval '(quicklisp-quickstart:install)' \
                --eval "(ql:quickload '(:quicklisp-slime-helper :clx :cl-ppcre :alexandria))" \
                --eval "(ql:quickload '(:xembed :xml-emitter :dbus :prove :swank))" \
                --eval "(quit)"
fi

exit
