#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# DEBUG OPTIONS
set -euo pipefail

# Description: make folders pointed by command followed by file
# Example: make_it.sh foo/bar/meh.sh bar/foo/file.py
# Shells supported: GNU Bash
# Inspiration: https://github.com/tanrax/terminal-AdvancedNewFile

# * VARS
ARGUMENTS=("$@")
PATH="${ARGUMENTS[0]}"
[[ "$#" -gt 1 ]] && VERBOSE="${ARGUMENTS[1]}"

# * FUNCTIONS
get_last_char() {
    echo "${PATH: -1}"
}

is_dir() {
    [[ $(get_last_char) == "/" ]]
}

get_filename() {
    echo "${PATH##*/}"
}

get_dir_path() {
    local result
    result=$(is_dir && echo "$PATH" || echo ${PATH%$(get_filename)})

    echo "$result"
}

create_dirs() {
    mkdir -p "$(get_dir_path)"
}

create_file() {
    echo '' >"$PATH"
}

run_verbose() {
    if [[ "$VERBOSE" == "--verbose" ]]; then
        echo <<EOF
Path      --> $PATH
Directory --> $(get_dir_path)
Filename  --> $(get_filename)
EOF
    fi
}

run() {
    run_verbose
    create_dirs
    create_file
}

# * MAIN
run
