#!/usr/bin/env bash
#
# Bin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bin. If not, see <https://www.gnu.org/licenses/>.
#

# Debug Options
set -euo pipefail

s_echo "Connect to Bluetooth Paired Devices"

DEPS=(bluetoothctl sudo sed grep)
s_checkdeps "${DEPS[@]}"

# autoenable
[[ ! $(grep 'AutoEnable=' /etc/bluetooth/main.conf) != '#AutoEnable=false' ]] &&
    /usr/bin/sudo /usr/bin/sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf

# poweron
# bluetoothctl power on

# connect
# bluetoothctl devices | awk '/Device/ {printf $2}' | xargs -I {} bluetoothctl 'connect {}'
